# Configuration for Hotfix: Cache invalidation bug in merchant data service
# Fixes critical bug where merchant profile updates were not properly invalidating cached data, leading to stale information in payment flows.

version: '1.0'
metadata:
  name: hotfix:-cache-invalidation-bug-in-merchant-data-service
  pr_id: 4
  created_at: "2025-08-06T15:17:53.052766"

settings:
  enabled: true
  timeout: 30
  retry_count: 3
  
features:
  - name: "enhanced_processing"
    enabled: true
    config:
      batch_size: 100
      parallel: true
  
  - name: "monitoring"
    enabled: true
    config:
      metrics_interval: 60
      log_level: "info"

database:
  pool_size: 10
  connection_timeout: 5000
  retry_attempts: 3

cache:
  enabled: true
  ttl: 300
  max_size: 1000
